Homework 1
Anzovi/Fault-Detection pull request #1
Opened 2024-10-27 13:14 UTC by Anzovi

Слияние ветки master и homework_1

2024-12-03 16:38 UTC, Uberwald commented
Хороший, проработанный док. Но почему нет раздела про пилот?

2024-12-04 09:03 UTC, Anzovi commented
> Хороший, проработанный док. Но почему нет раздела про пилот?

Спасибо за проверку! 
Для пилота пока рано, мы с командой в процессе создания baseline решения.

2024-12-16 08:06 UTC, Marsupilami-it commented
Исходя из самого домашнего задания, все пункты присутствуют.
Меня порадовало что уже начата работа, а так же что используется toml.
Единственное хотелось бы видеть архитектуру проекта чтобы понимать как вы видите развитие и где есть узкие горлышки.

2024-12-17 13:28 UTC, pacifikus requested changes
Добрый день!

Спасибо за работу! 

В целом все хорошо! Местами я оставила комментарии, где стоит немного поправить/доуточнить формулировки. Если будут вопросы - с радостью отвечу :)

2024-12-17 13:28 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- Что будем считать успехом итерации с точки зрения бизнеса: получение MVP системы по аналитике состояния оборудования и уведомлению об отклонениях и необходимости проведения технического обслуживани
Стоит немного уточнить бизнес-критерии успеха итерации: "получение MVP системы по аналитике..." - прямо вообще любого MVP? Константное предсказание, обернутое в красивый пайплайн тоже устроит? На данном этапе, как правило, у стейкхолдеров есть некоторые ориентиры по бизнес-метрикам, которые как раз стоит тут указать.

2024-12-17 13:28 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +  1. Модель должна, на основе собранных данных с сенсоров оборудования за определенный период времени, оповещать о необходимости проведения технического обслуживания.
За какой именно "определенный" период времени?

2024-12-17 13:28 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- Что мы ожидаем от конкретной итерации: создание инфраструктуры для сбора данных с сенсоров, установленных на оборудовании.
Здесь скорее ожидается, что именно с точки зрения ML разработки ожидается на данной итерации - пока что выглядит так, будто мы просто ждем, пока кто-то установит датчики на оборудование. Если это так, то можно указать текущий статус и написать, что планируется после их установки

2024-12-17 13:28 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- Описание бизнес-процесса пилота: модель будет оповещать инженеров о необходимости проведения технического обслуживания.
Пока что сам процесс оповещения непрозрачен. На этапе пилота это может выглядеть очень по-разному и значительно отличаться от целевого решения, а также от представлений заказчика, поэтому стоит конкретизировать, как именно будет выглядеть пилот, файлики с результатами по почте будут пересылаться, или сразу будут делать интеграции с конечными системами и т.п.

2024-12-17 13:28 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- Что считаем успешным пилотом? Критерии успеха и возможные пути развития проекта: предиктивное ТО успешно справляется с составлением графика проведения технических работ. Следовательно, решается зад
Опять же не очень понятно слово "успешно" - везде, что связано с критериями и Definition-of-Done нужны четкие цифры. Вполне вероятно, что ваше "успешно" и "успешно" бизнеса сильно отличаются...

2024-12-17 13:28 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- На закрытие каких БТ подписываемся в данной итерации: по небольшим выгрузкам данных с сенсоров провести анализ (EDA).
Просто проведение EDA не выглядит как бизнес-требование... Именно заказчикам сам EDA, как правило, не нужен, я бы предложила переформулировать данный пункт, указав, каую проблему EDA решает или какую цель закрывает - по его итогам будет приниматься решение о дальнейшей разработке модели? Может быть, эта аналитика поможет понять, как построить процесс генерации данных? Или что-то еще?

2024-12-17 13:28 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- Что не будет закрыто: на данной итерации не будет собрана модель предиктивного ТО, тк не достаточно данных для его реализации.
Здесь еще упомяну, что в рамках курса предполагается, что в следующих блоках какая-то модель/сервис чисто формально должны появиться, чтобы вы могли набрать необходимое количество баллов для завершения курса, поэтому стоит это учитывать в будущем

2024-12-17 13:28 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- Описание результата с точки зрения качества кода и воспроизводимости решения: на данный момент был произведен анализ по выгрузкам: в ветке main в папке /DA/Data_ForeCasting/ - тестирование различны
Здесь в целом все хорошо, но, просто немного нелогично. Дизайн-документ - это своего рода "чертеж здания", поэтому если в чертежах написано "Описание результата - на данный момент успешно сдан дом" это выглядит странно. Даже если у вас уже вся работа проделана, в этом пункте нужно описать требования к результату с точки зрения структуры/оформления и т.п.

2024-12-17 13:28 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- Описание результата с точки зрения качества кода и воспроизводимости решения: на данный момент был произведен анализ по выгрузкам: в ветке main в папке /DA/Data_ForeCasting/ - тестирование различны
Ну и в целом "тестирование" и "анализ" - это не результат, а процессы. Результат - те выводы и решения, которые после анализа вы можете сделать, а до - не могли...

2024-12-19 15:59 UTC, Anzovi commented on docs/ml_system_design_doc.md
> +- Что будем считать успехом итерации с точки зрения бизнеса: получение MVP системы по аналитике состояния оборудования и уведомлению об отклонениях и необходимости проведения технического обслуживани
Спасибо за корректировки! 
Буквально сегодня созвонились со стейкхолдерами и уточнил много важных деталей.

К сожалению у стейкхолдеров нет ориентиров по бизнес-метрикам (вся инфраструктура делается с нуля), тут скорее наша задача придумать наиболее подходящие. 

Так как данные на текущем этапе не отмечены (периоды проведения ТО, даты поломки оборудования, причины остановки оборудования, есть просто сырые данные - {дата, имя устройства, амперы}), то предсказание на длительный период RUL оборудования не получится (Не знаем когда конкретно случалась поломка и прочие события).

На данном этапе, можно предсказывать на небольшой период (уточняется какой длительности сигнала достаточно, чтобы сделать вывод о аномальности сигнала, точно сильно меньше 12 часов).  

Как это устроено сейчас - работник проверяет сигнал, накопленный за смену (12 часов). Если сигнал (в теории синусоида, на практике пилообразная форма с частыми всплесками - помехами) обладает постоянной амплитудой (модель будет это проверять), то всё нормально, если амплитуда не статична, то, очень вероятно, присутствует неполадка в оборудовании и модель должна оповестить об этом работника.

Требуется непосредственное присутствие работника, данные снимаются с нескольких машин, на каждой своя нагрузка, за всем сложно следить, автоматизация этого процесса и своевременное оповещение о аномалиях может сильно разгрузить работника.

Обновил дез док.

2024-12-19 15:59 UTC, Anzovi commented on docs/ml_system_design_doc.md
> +- Что считаем успешным пилотом? Критерии успеха и возможные пути развития проекта: предиктивное ТО успешно справляется с составлением графика проведения технических работ. Следовательно, решается зад
Помимо детекции аномального сигнала, которое можно свести к f1 метрике и сказать, что > 90 - отличный результат (на данном этапе пришли к такому выводу с стейкхолдерами), требуется в будущем решение задачи RUL (remaining useful life prediction).

У второй задачи есть свои метрики, но на текущем этапе разработки (разметки данных о состоянии оборудования для конкретного сигнала нет) эту задачу сложно решить.

2024-12-24 12:09 UTC, pacifikus approved these changes
Добрый день!

Спасибо за работу и комментарии! Теперь все отлично!

2024-12-25 05:50 UTC, merged